// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anpwgchrqtmokquaswiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFucHdnY2hycXRtb2txdWFzd2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTAxNzAsImV4cCI6MjA2MDA2NjE3MH0.31u921WKg0ctBDORWnU_1G5GJniuYFRA8-900pKLtsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);